### ISSUE TITLE
[linux] Flickering UI on canvas

### ISSUE THREAD

**Issue by gentlegiantJGC** [Amulet-Team/Amulet-Map-Editor#127]
Having potentially solved the renderer loading issue in #84 there is now a flicker from the canvas being redrawn.

This may solve the issue
http://wxpython-users.1045709.n5.nabble.com/wxPython-glcanvas-flickers-on-linux-td2275735.html

**Comment by EvilSupahFly** [comment]
[This thread on Nabble](http://wxpython-users.1045709.n5.nabble.com/wxPython-glcanvas-flickers-on-linux-td2275735.html) was opened in July 2000...

How much of it still applies to wxPython of 2020?

**Comment by gentlegiantJGC** [comment]
It may not. I hadn't noticed how old is was. I couldn't find anything else about it

**Comment by EvilSupahFly** [comment]
I found [this](https://gist.github.com/Ryex/f8c9df05a65d311aa6ec). Think you can make use of some of it?

**Comment by exo-core** [comment]
Another Linux user here, having the same issue on Ubuntu 20.04. The 3D view is rendered correctly, but all buttons and other overlays are flickering, making it basically impossible to use the editor. To give some idea about the used library versions:

```
$ python3 -m pip install amulet-map-editor
Requirement already satisfied: amulet-map-editor in ./lib/python3.8/site-packages (0.7.2.8)
Requirement already satisfied: pymctranslate~=1.0.0 in ./lib/python3.8/site-packages (from amulet-map-editor) (1.0.0.1)
Requirement already satisfied: amulet-nbt~=1.0.3 in ./lib/python3.8/site-packages (from amulet-map-editor) (1.0.3.4)
Requirement already satisfied: pyopengl==3.1.5 in ./lib/python3.8/site-packages (from amulet-map-editor) (3.1.5)
Requirement already satisfied: minecraft-resource-pack~=1.0.0 in ./lib/python3.8/site-packages (from amulet-map-editor) (1.0.2)
Requirement already satisfied: amulet-core~=1.0.0 in ./lib/python3.8/site-packages (from amulet-map-editor) (1.0.0.2)
Requirement already satisfied: numpy==1.17.4 in ./lib/python3.8/site-packages (from amulet-map-editor) (1.17.4)
Requirement already satisfied: wxPython==4.1.0 in ./lib/python3.8/site-packages (from amulet-map-editor) (4.1.0)
Requirement already satisfied: cython>=0.29.13 in ./lib/python3.8/site-packages (from amulet-nbt~=1.0.3->amulet-map-editor) (0.29.21)
Requirement already satisfied: Pillow>=7.1.0 in ./lib/python3.8/site-packages (from minecraft-resource-pack~=1.0.0->amulet-map-editor) (8.1.0)
Requirement already satisfied: six in ./lib/python3.8/site-packages (from wxPython==4.1.0->amulet-map-editor) (1.15.0)
```

Since I am already posting here: I also had some difficulties getting everything to compile, as there were some dependencies missing that were not resolved by pip. Installing `python3-dev`, `libgtk-3-dev`, `libwxbase3.0-dev` and libwxgtk3.0-gtk3-dev` and `python-sip-dev` solved the issue. Might be handy to mention those on the setup guide as well ;-)

**Comment by Moilleadoir** [comment]
I still get this bug. It makes Amulet very hard to use when you can’t see the toolbars.

OS: Manjaro Cinnamon
Amulet: 0.8.7

**Comment by samdejong86** [comment]
Having this on Ubuntu 18.04, Python 3.8, amulet 0.8.7

**Comment by EnricoMonese** [comment]
I think I have a similar issue but on macOS 10.13 High Sierra. The toolbars are only visible during the flickering that happens only when resizing the window. 

https://user-images.githubusercontent.com/19847464/123715404-85f47e00-d878-11eb-968c-014f52406b6c.mp4

**Comment by Neubulae** [comment]
Having this on Arch Linux, Python 3.9.6, Amulet 0.8.11

**Comment by leucome** [comment]
Is there somebody who do not have this issue on linux?

**Comment by simisimis** [comment]
NixOS with mesa. python 3.8-3.9. invisible toolbox unless I am shaking cursor.

**Comment by giray** [comment]
Ubuntu 21.04 Python 3.9.5 Amulet 0.8.12
Menu items constantly flicker, tried both with and without virtual environment.

**Comment by gentlegiantJGC** [comment]
I am looking to make the switch to Qt which will hopefully solve this issue and remove some other restrictions. Before I do I want to make sure that it is actually going to solve the issue. Please can all of you try running this demo that adds a button on top of the Qt opengl demo and let me know if it works or not.
https://gist.github.com/gentlegiantJGC/3681c8eaa5e9707bf60d4c5ab0613595
![image](https://user-images.githubusercontent.com/11940194/131257591-a53e6265-62a7-4071-82ab-f6aaa12a64bb.png)

**Comment by Cebtenzzre** [comment]
@gentlegiantJGC The demo renders fine for me.

**Comment by gentlegiantJGC** [comment]
What OS are you using?

**Comment by EvilSupahFly** [comment]
> @gentlegiantJGC The demo renders fine for me.

> What OS are you using?

I'm curious as well. I'm using Cinnamon 5.0.5 with muffin and LightDM on Linux Mint 20.2, which is based on Ubuntu 20.04 focal and I'm running Kernel 5.13-051300-generic (x64). My GPU is an NVIDIA GeForce GTX 1660 and I'm running the official driver: nvidia 470.57.02

**Comment by Cebtenzzre** [comment]
@gentlegiantJGC Arch Linux, linux-ck 5.12.19, GTX 970 with nvidia 470.63.01, Qt 6.1.2.

**Comment by Moilleadoir** [comment]
Runs fine for me in a virtual env with those prereqs.

Manjaro + Cinnamon desktop 5.0.5
Kernel 5.10.60-1 (LTS)
NVIDIA GeForce GTX 1070 + driver 470.63.01

**Comment by uiytt** [comment]
I had the problem on Amulet, but the demo you gave works fine in env.

PopOs (=> Ubuntu) + Kde :  Qt : 5.15.2
Kernel Linux 5.11.0-7620-generic x86_64
NVIDIA GTX 1050 + driver 470.57.02 from PopOs

**Comment by EvilSupahFly** [comment]
As you can see in my dual-monitor screenshot below, the demo runs fine on my Manjaro KDE VM, but not my Mint Gnome host, and I suspect my problem lies in there somewhere, as KDE is built using QT while my host is GTK+. I haven't had the time to really dig in to it to find out what's going on.

![Screenshot from 2021-08-31 14-02-20](https://user-images.githubusercontent.com/3280846/131696182-b2cf51ed-bc42-4dd3-8f38-9c56d5b8bace.png)

**Comment by exo-core** [comment]
Tested it on Ubuntu 20.4 and it works fine with both, Ubuntu's native Gnome desktop as well as Cinnamon.
Hardware info below.

```
arne@T420:~$ neofetch
            .-/+oossssoo+/-.               arne@T420 
        `:+ssssssssssssssssss+:`           --------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.3 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 4180PH3 ThinkPad T420 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.11.0-27-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 3 days, 7 hours, 54 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3613 (dpkg), 11 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 2560x1440 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Cinnamon 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter (Muffin) 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: (Default) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Adwaita-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Faenza-Darker [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-2720QM (8) @ 3.300GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA Quadro NVS 4200M 
      -+sssssssssssssssssyyyssss+-         Memory: 2528MiB / 15963MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                   
```

**Comment by Dracon23** [comment]
Same issue here, using Manjaro Linux ([sysinfo](https://pastebin.com/DxWGF929) - Python 3.9 ([VEnv packages](https://pastebin.com/AiRrkBxj)).

Demo runs well

**Comment by processor286** [comment]
Overlays are all wrong on my Manjaro installation,  the demo works fine.  Specs:
```

██████████████████  ████████   
██████████████████  ████████   ---------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: MS-7C56 1.0 
████████            ████████   Kernel: 5.10.61-1-MANJARO 
████████  ████████  ████████   Uptime: 1 day, 13 hours, 55 mins 
████████  ████████  ████████   Packages: 1588 (pacman), 19 (flatpak), 9 (snap) 
████████  ████████  ████████   Shell: zsh 5.8 
████████  ████████  ████████   Resolution: 3840x2160 
████████  ████████  ████████   DE: GNOME 40.4 
████████  ████████  ████████   WM: Mutter 
████████  ████████  ████████   WM Theme: Adwaita-maia-compact-dark 
████████  ████████  ████████   Theme: Adwaita-maia-compact [GTK2/3] 
████████  ████████  ████████   Icons: Papirus-Dark-Maia [GTK2/3] 
                               Terminal: gnome-terminal 
                               CPU: AMD Ryzen 5 3600X (12) @ 3.800GHz 
                               GPU: AMD ATI Radeon R9 285/380 
                               Memory: 4506MiB / 32094MiB 
```

**Comment by lionkor** [comment]
Still an unresolved issue.
* Arch Linux x86_64
* Kernel 5.14.6
* X11
* NVidia

**Comment by EvilSupahFly** [comment]
I suffered a catastrophic drive failure, and I'm waiting for my replacement to arrive. Once it's here, and I've reinstalled my core OS, I'll take this for another spin while the system is clean.

**Comment by PixelRave** [comment]
I have the same issue on Mint OS, no menu in the 3D editor and its flickering like crazy.

**Comment by hyperstown** [comment]
> I am looking to make the switch to Qt which will hopefully solve this issue and remove some other restrictions. Before I do I want to make sure that it is actually going to solve the issue. Please can all of you try running this demo that adds a button on top of the Qt opengl demo and let me know if it works or not. Before running you will need to install PySide6, PyOpenGL and numpy https://gist.github.com/gentlegiantJGC/3681c8eaa5e9707bf60d4c5ab0613595 ![image](https://user-images.githubusercontent.com/11940194/131257591-a53e6265-62a7-4071-82ab-f6aaa12a64bb.png)

Demo works without an issue.
``` 
DE: KDE Plasma 5.23.4
QT version: 5.15.2
Kernel: 5.15
OS: Arch
```

**Comment by polyzium** [comment]
Manjaro, KDE Plasma 5.23.4, Qt 5.15.2. Works as expected.
![image](https://user-images.githubusercontent.com/22579935/146833094-3c5b59d7-299f-42e2-bb1b-bcdc3c4f33a0.png)

**Comment by uiytt** [comment]
Works perfectly 
```
DE: Gnome 40.0
Kernel: 5.15.5
OS: Pop 21.10
```

**Comment by ShockedCoder** [comment]
Demo works perfectly
![demo image](https://user-images.githubusercontent.com/40272709/183483076-20e4e2cb-8bc5-4896-8def-07af37054719.png)
```
DE: Xfce 4.16
Kernel: 5.10.131-1-MANJARO
OS: Manjaro Linux x86_64
```

**Comment by sbock17** [comment]
Hello same issue with amulet running Arch Linux, has there been any success with arch-based distro so far / are there working workarounds for anyone?

Kind regards

**Comment by Avakining** [comment]
Demo works mostly correctly on macOS 13.1 (arm64)

As shown in this [screen recording](https://youtu.be/kmiZ_yKNzVY), it renders correctly when moving the object, but flickers slightly when changing the window size. This shouldn't be too much of an issue, however

**Comment by yri066** [comment]
Demo runs well
![Снимок экрана 2023-02-04 в 12 54 53](https://user-images.githubusercontent.com/26645205/216760830-f331cdcd-feab-452d-85b3-928613bc15cb.png)

**Comment by 3l4d3** [comment]
Having this issue right now. UI only flickers/shows when resizing the window.

Every time the UI shows, the following is printed to the terminal running the application.

```
(__main__.py:223125): Gtk-WARNING **: 18:22:37.754: Negative content width -10 (allocation 4, extents 7x7) while allocating gadget (node button, owner GtkButton)

(__main__.py:223125): Gtk-WARNING **: 18:24:05.364: Negative content width -4 (allocation 10, extents 7x7) while allocating gadget (node button, owner GtkButton)

(__main__.py:223125): Gtk-WARNING **: 18:24:13.394: Negative content width -6 (allocation 8, extents 7x7) while allocating gadget (node button, owner GtkButton)

(__main__.py:223125): Gtk-WARNING **: 18:24:14.165: Negative content width -11 (allocation 3, extents 7x7) while allocating gadget (node button, owner GtkButton)

(__main__.py:223125): Gtk-WARNING **: 18:24:14.712: Negative content width -4 (allocation 10, extents 7x7) while allocating gadget (node button, owner GtkButton)
```

**My computer specs**

OS: Manjaro Linux x86_64 
Kernel: 6.1.29-1-MANJARO 
Resolution: 3840x2160 
DE: Plasma 5.27.4 
WM: KWin 
CPU: Intel i7-6700K (8) @ 4.200GHz 
GPU: NVIDIA GeForce GTX 980 Ti 
Memory: 6123MiB / 11880MiB

**Comment by ShockedCoder** [comment]
Is this bug present on all Linux OSes or does it work just fine for some people?

If there's anyone who's using Linux and has no problems with Amulet, please leave a reply and tell us your distro.

**Comment by lionkor** [comment]
> Works perfectly
> 
> ```
> DE: Gnome 40.0
> Kernel: 5.15.5
> OS: Pop 21.10
> ```

looks like amulet works for @uiytt ?

**Comment by PackmanDude** [comment]
> Another Linux user here, having the same issue on Ubuntu 20.04. The 3D view is rendered correctly, but all buttons and other overlays are flickering, making it basically impossible to use the editor. To give some idea about the used library versions:
> 
> ```
> $ python3 -m pip install amulet-map-editor
> Requirement already satisfied: amulet-map-editor in ./lib/python3.8/site-packages (0.7.2.8)
> Requirement already satisfied: pymctranslate~=1.0.0 in ./lib/python3.8/site-packages (from amulet-map-editor) (1.0.0.1)
> Requirement already satisfied: amulet-nbt~=1.0.3 in ./lib/python3.8/site-packages (from amulet-map-editor) (1.0.3.4)
> Requirement already satisfied: pyopengl==3.1.5 in ./lib/python3.8/site-packages (from amulet-map-editor) (3.1.5)
> Requirement already satisfied: minecraft-resource-pack~=1.0.0 in ./lib/python3.8/site-packages (from amulet-map-editor) (1.0.2)
> Requirement already satisfied: amulet-core~=1.0.0 in ./lib/python3.8/site-packages (from amulet-map-editor) (1.0.0.2)
> Requirement already satisfied: numpy==1.17.4 in ./lib/python3.8/site-packages (from amulet-map-editor) (1.17.4)
> Requirement already satisfied: wxPython==4.1.0 in ./lib/python3.8/site-packages (from amulet-map-editor) (4.1.0)
> Requirement already satisfied: cython>=0.29.13 in ./lib/python3.8/site-packages (from amulet-nbt~=1.0.3->amulet-map-editor) (0.29.21)
> Requirement already satisfied: Pillow>=7.1.0 in ./lib/python3.8/site-packages (from minecraft-resource-pack~=1.0.0->amulet-map-editor) (8.1.0)
> Requirement already satisfied: six in ./lib/python3.8/site-packages (from wxPython==4.1.0->amulet-map-editor) (1.15.0)
> ```
> 
> Since I am already posting here: I also had some difficulties getting everything to compile, as there were some dependencies missing that were not resolved by pip. Installing `python3-dev`, `libgtk-3-dev`, `libwxbase3.0-dev`, `libwxgtk3.0-gtk3-dev` and `python-sip-dev` solved the issue. Might be handy to mention those on the setup guide as well ;-)

pip is dumb bullshit, never works

**Comment by Kcraft059** [comment]
Also Having the same issue on MacOs 10.14 Mojave the Tool bar only show when re-sizing the window it's like an overlapping issue maybe it can be resolved by showing the menu in a separate window.

https://github.com/Amulet-Team/Amulet-Map-Editor/assets/137693466/16e37f26-e97a-4253-bf9e-dda604a5d964

**Comment by randoogle** [comment]
Not sure if it's worth mentioning, but the symptoms of this using Wayland are a bit different. Instead of a flickering UI, it seems as though the UI is behind the render screen. You can only catch glimpses of it when doing selections on nearby objects:
![Screenshot from 2023-07-03 23-45-13](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/347056/443c3a0e-d202-408d-8980-4bfa1980bd3a)
When I switch from wayland to xorg, I see the same flickering during resizing behavior that everyone else is reporting.

**Comment by Endersirio** [comment]
Any news?
I have the same problem

**Comment by Xalalau** [comment]
2024, same issue. Linux Mint 21.3.

And I needed to install a missing dependency to be able to open the maps: sudo apt-get install freeglut3-dev

**Comment by EvelynMakesThings** [comment]
I share a similar issue, kali linux.
![Screenshot_2024-03-27_09_56_17](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/99486014/c65deefa-b6e5-48fb-a1b1-0587b90da2f2)
UI flickers into existence as I move the camera, otherwise the UI is invisible. Appears like z-fighting. Note, the ui can still be interacted with even if it is not visible.

**Comment by Sharparam** [comment]
As a workaround, is it possible to just make the 3D viewport smaller so that the UI controls no longer overlay it and become usable?

**Comment by ghost** [comment]
![image](https://github.com/Amulet-Team/Amulet-Map-Editor/assets/123738491/85b24e99-c17a-4ec4-b870-8bb112d01df1)

Same issue.

Debian 12.6 with DWM
Python 3.11.2
Amulet Map Editor 0.10.34

**Comment by Random-Penguin** [comment]
Same issue

L4T Ubuntu Noble 24.04
NVidia Tegra X1
Python 3.12
Amulet 0.10.35

**Comment by EvilSupahFly** [comment]
In testing 0.10.37 while preparing the Flatpak update, I've noticed that Amulet will often crash three or four times after clicking "3D Editor" once a world is loaded. However, I have noticed that if I give it on average two minutes before clicking, it will usually load just fine. I don't know why there's a time-delay, and there's not always an error message in the terminal when it quits - acting almost like it was simply a user-initiated shut down. I've tested seven different Worlds all saved in different Minecraft versions, but the results were all fairly consistent on both my EndeavourOS test rig (Arch based) and my primary Mint build rig (Ubuntu/Debian based).

If you want a debug log, let me know and I'll attach it.

**Comment by EvilSupahFly** [comment]
On EndeavourOS (KDE Plasma, Wayland), the GUI doesn't flicker, but it is 90% transparent and the buttons don't "light up" or provide any other response when the mouse hovers over them.

![Screenshot from 2024-11-25 08-45-07](https://github.com/user-attachments/assets/babe7a59-141f-4fa4-aa99-6de6903f0872)

**Comment by catthou** [comment]
I'm having this issue right now on Gentoo Linux. Openbox on X11, nvidia graphics 550.142, Python 3.11.11

The UI only shows up when I'm moving the camera around.

**Comment by doublej74** [comment]
Same issue on linux mint 22.1

**Comment by DudenessBoy** [comment]
It also seems to happen to me. Why haven't the devs fixed this in like 4 years?

**Comment by Random-Penguin** [comment]
Maybe because you might have to rewrite the whole GUI if moving to Qt? Or maybe because people aren't as active here as before or like with oher projects... Either way, if you want to contribute, go ahead; it would help us all.

**Comment by EvilSupahFly** [comment]
> It also seems to happen to me. Why haven't the devs fixed this in like 4 years?

Because it's an issue with the underlying wxPython framework and this is basically a volunteer project.

**Comment by jadenquinn** [comment]
I can't even get it to find and install.

**Comment by EvilSupahFly** [comment]
> I can't even get it to find and install.

Amulet itself? As in... the [<> Code](https://github.com/Amulet-Team/Amulet-Map-Editor) tab with the README.MD that explains literally everything?

**Comment by jadenquinn** [comment]
> > I can't even get it to find and install.
> 
> Amulet itself? As in... the [<> Code](https://github.com/Amulet-Team/Amulet-Map-Editor) tab with the README.MD that explains literally everything?

Yes, that. It can't find the program.

**Comment by EvilSupahFly** [comment]
You click the Code tab, which I linked to above, and you pick one of these options pictured below if you're on Linux or Mac, and you follow the instructions in the [README.md](https://github.com/Amulet-Team/Amulet-Map-Editor) underneath the table of files.

![Image](https://github.com/user-attachments/assets/9dacd661-75e1-4d17-ace5-3dbe27e09f38)

**Comment by jadenquinn** [comment]
run python -m pip install amulet-map-editor to install the library and all its dependencies.
run python -m amulet_map_editor to run the program

These commands do not work for me.

**Comment by gentlegiantJGC** [comment]
@jadenquinn @EvilSupahFly this is off-topic for this issue. You already have an issue open for your problem #1164

**Comment by jadenquinn** [comment]
> > It also seems to happen to me. Why haven't the devs fixed this in like 4 years?
> 
> Because it's an issue with the underlying wxPython framework and this is basically a volunteer project.

Well I mean if it's a volunteer project, it's easier to halt development until stable versions of the libraries used can be utilized to build upon... don't start stuff you can't finish. Never ends well.

**Comment by thespragg** [comment]
> > > It also seems to happen to me. Why haven't the devs fixed this in like 4 years?
> > 
> > 
> > Because it's an issue with the underlying wxPython framework and this is basically a volunteer project.
> 
> Well I mean if it's a volunteer project, it's easier to halt development until stable versions of the libraries used can be utilized to build upon... don't start stuff you can't finish. Never ends well.

Linux is likely a very small subset of the users of this tool and lets be real its a 20 minute job to spin up a VM if you really care that much. As the other commenter said, its been 4 years since the dependant library hasnt worked but Id be willing to bet if they dropped linux support you'd just whinge that its been windows only for 4 years.

**Comment by gentlegiantJGC** [comment]
A user has submitted a fix for this but I haven't gotten around to testing it.
https://github.com/Amulet-Team/Amulet-Map-Editor/pull/1150

Can some users please verify if this fixes the issue.

**Comment by thespragg** [comment]
> A user has submitted a fix for this but I haven't gotten around to testing it. [#1150](https://github.com/Amulet-Team/Amulet-Map-Editor/pull/1150)
> 
> Can some users please verify if this fixes the issue.

Ive just pulled the fork down and tested it, as far as I can see its working on Kubuntu 24.04

**Comment by Random-Penguin** [comment]
> A user has submitted a fix for this but I haven't gotten around to testing it. [#1150](https://github.com/Amulet-Team/Amulet-Map-Editor/pull/1150)
> 
> Can some users please verify if this fixes the issue.

This took a while to get going due to #1105 (fixed using `apt install freeglut3-dev` method), but it works as good as it can get on a Nintendo Switch...

Running on X11

![Image](https://github.com/user-attachments/assets/302a0462-59cb-4b22-9c6a-c96b18e3d609)

**Comment by jadenquinn** [comment]
> > > > It also seems to happen to me. Why haven't the devs fixed this in like 4 years?
> > > 
> > > 
> > > Because it's an issue with the underlying wxPython framework and this is basically a volunteer project.
> > 
> > 
> > Well I mean if it's a volunteer project, it's easier to halt development until stable versions of the libraries used can be utilized to build upon... don't start stuff you can't finish. Never ends well.
> 
> Linux is likely a very small subset of the users of this tool and lets be real its a 20 minute job to spin up a VM if you really care that much. As the other commenter said, its been 4 years since the dependant library hasnt worked but Id be willing to bet if they dropped linux support you'd just whinge that its been windows only for 4 years.

VM? Are you out of your mind? It likely doesn't even work under a VM without GPU passthrough (Not even Ultimate Doom Builder works under Parallels) Why even bother with the program at all then? I'd just go outside and talk to people at that point. That's one of the most out of touch things I've ever seen anyone say ,and it's rare that I get pissed off at GitHub comments of all things. Start a VM to use one program.. what absolute nonsense - And that would only be for power users.

On the other hand, yea I've seen a lot of devs that had support, but just dropped MacOS and Linux. It happens often enough that a few things I used to use had this happen. I do understand why this happens and that there's not much one can do about it other than continue developing it THEMSELVES.

**Comment by EvilSupahFly** [comment]
You can run Amulet in a VM as long as you have OpenGL 3D acceleration enabled but it's not as fast as running natively and running a VM has its own set of problems. I'd rather put up with the flickering than deal with the extra overhead and problems a VM can add.

**Comment by jadenquinn** [comment]
Same

**Comment by gentlegiantJGC** [comment]
I think #1203 should mostly fix this issue.
Please can someone try it on linux and let me know if it works.

**Comment by Random-Penguin** [comment]
This commit doesn't work for me, which is weird since #1150 worked.
I ran these commands to add the commit, tell me if I'm wrong.
```
git clone https://github.com/Amulet-Team/Amulet-Map-Editor
git remote set-branches --add origin master
git checkout origin/fix-127
```
Here's a janky recording:
https://github.com/user-attachments/assets/6e72ab19-633b-4ad0-b9ac-891032bf2f78

**Comment by gentlegiantJGC** [comment]
Does it behave differently to the current behaviour?
You can verify by checking if the file matches these changes.
https://github.com/Amulet-Team/Amulet-Map-Editor/pull/1203/files

**Comment by Random-Penguin** [comment]
Last I checked, it is different, due to this pull not only flickering while interacting with the editor, but even when not doing anything, which didn't happen on non-patched Amulet.

I can confirm I'm using the right files.

**Comment by gentlegiantJGC** [comment]
Hmm okay. It was worth a try.
I will look into cleaning up #1150

**Comment by KBOX1234** [comment]
Why is this still an issue?

**Comment by gentlegiantJGC** [comment]
It is a compositing issue with the underlying widget library.
#1150 is a workaround for this issue.

**Comment by Xalalau** [comment]
Minecraft has proper Linux support now. Ty.

**Comment by EvilSupahFly** [comment]
> Minecraft has proper Linux support now. Ty.

Minecraft has always had proper Linux support. Amulet had issues with the Canvas on Linux because Windows, X-Windows, and Wayland all handled the canvas differently.

**Comment by Xalalau** [comment]
> > Minecraft has proper Linux support now. Ty.
> 
> Minecraft has always had proper Linux support. Amulet had issues with the Canvas on Linux because Windows, X-Windows, and Wayland all handled the canvas differently.

Do I really need to explain that I wanted to praise the software and that I don't need to be told what the bug was?
