### ISSUE TITLE
Distribute Amulet as a flatpak

### ISSUE THREAD

**Issue by TerminallyDied** [Amulet-Team/Amulet-Map-Editor#525]
**Is your feature request related to a problem? Please describe.**
its very annoying to install Amulet on linux without using the terminal and it taking a very long time to compile, with a flatpak you it will be very easy to install Amulet and you wont need to worry about what distro someone is using because flatpaks work on almost all populair distros see https://flatpak.org/setup/

**Describe the solution you'd like**
add an Amulet as an Flatpak
https://github.com/flathub/flathub/wiki/App-Submission

**Describe alternatives you've considered**
provide an .deb and or .rpm file which are both distro limited but better then nothing

**Comment by oneechanhax** [comment]
I made a very simple build script. It doesn't do proper build sandboxing but I did it mainly for .file/general clutter containment and sandboxing. Build at your own risk!!!
You may try flatpak-pip-generator but I had issues around numpy being weird with amulet-nbt so I gave up with the sandboxing.

``` 
$ cat com.amulet.AmuletMC.json
{
    "app-id": "com.amulet.AmuletMC",
    "runtime": "org.freedesktop.Platform",
    "runtime-version": "21.08",
    "sdk": "org.freedesktop.Sdk",
    "command": "amuletmc-flatpak-entry.sh",
    "finish-args": [
        "--socket=x11",
        "--socket=wayland",
        "--device=dri",
        "--filesystem=~/.minecraft/saves",
        "--filesystem=~/.var/app/org.polymc.PolyMC/data/polymc/instances/*/saves"
    ],
    "modules": [{
        "name": "python3-amulet-map-editor",
        "buildsystem": "simple",
        "build-commands": [
           "pip3 install --verbose --prefix=/app amulet-map-editor"
        ],
        "build-options": {
           "build-args": [ "--share=network" ]
        },
        "sources": []
    }, {
        "name": "amuletmc-flatpak-entry",
        "buildsystem": "simple",
        "build-commands": [
            "install -D amuletmc-flatpak-entry.sh /app/bin/amuletmc-flatpak-entry.sh"
        ],
        "sources": [{
            "type": "file",
            "path": "amuletmc-flatpak-entry.sh"
        }]
    }]
}
```
``` 
$ cat amuletmc-flatpak-entry.sh
#!/bin/bash
export PYTHONPATH="/app"

python3 -m amulet_map_editor
```
Ran with `flatpak-builder --user --install --force-clean tmp/ com.amulet.AmuletMC.json`
GPL3 pls

Also,  Im not sure if the install script is broken, permissions, or my gpu but I do get an error when the 3d editor is opened.
Could be how its installed to a nonstandard folder but I don't know much about how python likes its file layouts with pip.
```
<class 'wx._glcanvas.GLAttributes'> returned a result with an error set
NotImplementedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/amulet_map_editor/api/framework/pages/world_page.py", line 155, in _enable_active
    self._extensions[self.GetSelection()].enable()
  File "/app/lib/python3.9/site-packages/amulet_map_editor/programs/edit/edit.py", line 50, in enable
    self._canvas = EditCanvas(self, self._world, self._close_self_callback)
  File "/app/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/canvas/edit_canvas.py", line 92, in __init__
    super().__init__(parent, world)
  File "/app/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py", line 58, in __init__
    super().__init__(parent)
  File "/app/lib/python3.9/site-packages/amulet_map_editor/api/opengl/canvas/event_canvas.py", line 12, in __init__
    super().__init__(parent)
  File "/app/lib/python3.9/site-packages/amulet_map_editor/api/opengl/canvas/canvas.py", line 23, in __init__
    display_attributes = wx.glcanvas.GLAttributes()
SystemError: <class 'wx._glcanvas.GLAttributes'> returned a result with an error set

/app/bin/amuletmc-flatpak-entry.sh: line 4:     3 Segmentation fault      (core dumped) python3 -m amulet_map_editor
```

**Comment by kargaroc** [comment]
This is sorely needed on systems where the bundled python interpreter is too new

**Comment by PixelRave** [comment]
Having a flatpak would make this much easier to distribute to Linux. On top of automatic updates. It would be a no brainier to use.

**Comment by gentlegiantJGC** [comment]
We are in the process of rebuilding Amulet in Qt (a different UI library) and I will implement this there.
We are not currently implementing new functionality for the current Amulet implementation.

We have this which should be able to make these files
https://github.com/Amulet-Team/python-build-tool

**Comment by nl255** [comment]
Having a flatpak would also make it much easier to run on the Steam Deck.

**Comment by JakobDev** [comment]
Any news on this?

I have experience in Flatpak, so I can help you, if you want.

**Comment by nl255** [comment]
I will say that I was unable to install this normally on the Steam Deck at all since it requires so many packages (gcc, all sorts of headers and -dev library packages, etc) to be installed that I eventually gave up even after disabling the read only filesystem and installing a bunch of stuff with pacman.

**Comment by Xalalau** [comment]
> I made a very simple build script. It doesn't do proper build sandboxing but I did it mainly for .file/general clutter containment and sandboxing. Build at your own risk!!! You may try flatpak-pip-generator but I had issues around numpy being weird with amulet-nbt so I gave up with the sandboxing.
> 
> ```
> $ cat com.amulet.AmuletMC.json
> {
>     "app-id": "com.amulet.AmuletMC",
>     "runtime": "org.freedesktop.Platform",
>     "runtime-version": "21.08",
>     "sdk": "org.freedesktop.Sdk",
>     "command": "amuletmc-flatpak-entry.sh",
>     "finish-args": [
>         "--socket=x11",
>         "--socket=wayland",
>         "--device=dri",
>         "--filesystem=~/.minecraft/saves",
>         "--filesystem=~/.var/app/org.polymc.PolyMC/data/polymc/instances"
>     ],
>     "modules": [{
>         "name": "python3-amulet-map-editor",
>         "buildsystem": "simple",
>         "build-commands": [
>            "pip3 install --verbose --prefix=/app amulet-map-editor"
>         ],
>         "build-options": {
>            "build-args": [ "--share=network" ]
>         },
>         "sources": []
>     }, {
>         "name": "amuletmc-flatpak-entry",
>         "buildsystem": "simple",
>         "build-commands": [
>             "install -D amuletmc-flatpak-entry.sh /app/bin/amuletmc-flatpak-entry.sh"
>         ],
>         "sources": [{
>             "type": "file",
>             "path": "amuletmc-flatpak-entry.sh"
>         }]
>     }]
> }
> ```
> 
> ```
> $ cat amuletmc-flatpak-entry.sh
> #!/bin/bash
> export PYTHONPATH="/app"
> 
> python3 -m amulet_map_editor
> ```
> 
> Ran with `flatpak-builder --user --install --force-clean tmp/ com.amulet.AmuletMC.json` GPL3 pls
> 
> Also, Im not sure if the install script is broken, permissions, or my gpu but I do get an error when the 3d editor is opened. Could be how its installed to a nonstandard folder but I don't know much about how python likes its file layouts with pip.
> 
> ```
> <class 'wx._glcanvas.GLAttributes'> returned a result with an error set
> NotImplementedError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/app/lib/python3.9/site-packages/amulet_map_editor/api/framework/pages/world_page.py", line 155, in _enable_active
>     self._extensions[self.GetSelection()].enable()
>   File "/app/lib/python3.9/site-packages/amulet_map_editor/programs/edit/edit.py", line 50, in enable
>     self._canvas = EditCanvas(self, self._world, self._close_self_callback)
>   File "/app/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/canvas/edit_canvas.py", line 92, in __init__
>     super().__init__(parent, world)
>   File "/app/lib/python3.9/site-packages/amulet_map_editor/programs/edit/api/canvas/base_edit_canvas.py", line 58, in __init__
>     super().__init__(parent)
>   File "/app/lib/python3.9/site-packages/amulet_map_editor/api/opengl/canvas/event_canvas.py", line 12, in __init__
>     super().__init__(parent)
>   File "/app/lib/python3.9/site-packages/amulet_map_editor/api/opengl/canvas/canvas.py", line 23, in __init__
>     display_attributes = wx.glcanvas.GLAttributes()
> SystemError: <class 'wx._glcanvas.GLAttributes'> returned a result with an error set
> 
> /app/bin/amuletmc-flatpak-entry.sh: line 4:     3 Segmentation fault      (core dumped) python3 -m amulet_map_editor
> ```

The ``SystemError: <class 'wx._glcanvas.GLAttributes'> returned a result with an error set`` issue was solved here: 
 https://github.com/Amulet-Team/Amulet-Map-Editor/issues/449

**Comment by bokov** [comment]
> We are in the process of rebuilding Amulet in Qt (a different UI library) and I will implement this there. We are not currently implementing new functionality for the current Amulet implementation.
> 
> We have this which should be able to make these files https://github.com/Amulet-Team/python-build-tool

Sorry for being dense and needing things spelled out. I'm not used to dealing with multiple versions of Python.

Is the current workaround to follow the steps in https://github.com/Amulet-Team/Amulet-Map-Editor/issues/525#issuecomment-1013959025 ?  If so, how does the python-build-tool fit into this?

Or do you recommend downloading the latest development snapshot of your QT version? If so, which repo/branch is that?

Thank you.

**Comment by gentlegiantJGC** [comment]
Check out #1070

**Comment by EvilSupahFly** [comment]
As noted in #1070, I did manage to make a Flatpak build of Amulet (see https://github.com/EvilSupahFly/Amulet-Flatpak), currently based on Amulet 0.10.36

**Comment by signalno11** [comment]
I'd like to second this. After paying for your software, I'm rather disappointed to find out that I have to mess around with Docker to get your application working, when Flatpak is a well established, containerized, consistent runtime system for GUI apps. Docker seems to be woefully the wrong route. Please look into how to package for Flatpak, it's not difficult.

**Comment by gentlegiantJGC** [comment]
I will look into it. I am not a Linux user so all of this is new to me.
Last week I added `.deb` installers which work with Ubuntu 24.04. I am unsure if it works with other flavours of Linux.
The docker implementation was submitted by a user.

**Comment by signalno11** [comment]
> I will look into it. I am not a Linux user so all of this is new to me.
> Last week I added `.deb` installers which work with Ubuntu 24.04. I am unsure if it works with other flavours of Linux.
> The docker implementation was submitted by a user.

Ah, fair enough. .deb packages are Debian specific.
Flatpak would be an ideal solution, since it works on all distros.

Additionally, I think most users would find it helpful if you distributed the software on Flathub, https://docs.flathub.org/docs/category/for-app-authors.

As far as runtimes, if you're not using any GNOME or KDE tooling, just build the app with the freedesktop runtime. Using whatever you have for tthe OCI container should also work here, I think.

**Comment by EvilSupahFly** [comment]
> > I will look into it. I am not a Linux user so all of this is new to me.
> > Last week I added `.deb` installers which work with Ubuntu 24.04. I am unsure if it works with other flavours of Linux.
> > The docker implementation was submitted by a user.
> 
> Ah, fair enough. .deb packages are Debian specific. Flatpak would be an ideal solution, since it works on all distros.
> 
> Additionally, I think most users would find it helpful if you distributed the software on Flathub, https://docs.flathub.org/docs/category/for-app-authors.
> 
> As far as runtimes, if you're not using any GNOME or KDE tooling, just build the app with the freedesktop runtime. Using whatever you have for tthe OCI container should also work here, I think.

I have some time off work over Easter and plan to revisit my flatpak implementation. It worked, **mostly**, as of Amulet 0.10.42, except that the bundled textures don't load (water, lava, etc) and I'm **_STILL_** not sure why. The flickering was fixed though thanks to that patch by [Ryan3141](https://github.com/Ryan3141/Amulet-Map-Editor).

**Comment by gentlegiantJGC** [comment]
> I think most users would find it helpful if you distributed the software on Flathub

Looks like they are looking into supporting paid software but don't currently. I can't see any way to make it work with our current licencing model that does not involve adding some kind of DRM to the software which I don't want to do. For now I will continue uploading the files to gumroad.


> The flickering was fixed though thanks to that patch by [Ryan3141](https://github.com/Ryan3141/Amulet-Map-Editor).

I implemented the concept of that patch into the main branch so the main branch should just work. The patch itself was a bit more of a hack than I liked. I ended up refactoring all the GUI elements to not be children of the canvas and do manual resizing instead of using layouts.

I will look into flatpak today.

**Comment by signalno11** [comment]
Ah, I didn't realize that you weren't already using some sort of license system. 


See https://docs.flatpak.org/en/latest/hosting-a-repository.html for making a repo. You needn't anything fancy, you can do it right here on GH Pages.

However, authentication still isn't supported yet, I think, so you can also distribute .flatpak files on gum road

**Comment by nl255** [comment]
How about an AppImage which can then be provided the same way as any other installer/executable?

**Comment by signalno11** [comment]
> How about an AppImage which can then be provided the same way as any other installer/executable?

AppImages are alright, but Flatpaks can be distributed without a repo, so I see no reason to opt for AppImages, given that they're plagued with issues, from relying on the [practically ancient fuse2 library](https://github.com/libfuse/libfuse/releases/tag/fuse-2.9.9), their poor handling of libraries, not being integrated well (yes, you can use 3rd party tools), etc. 

You can find [plenty](https://ludditus.com/2024/10/31/appimage/) of [different](https://github.com/boredsquirrel/dont-use-appimages) people talking about how annoying and flawed AppImages are as a format.

Opt for Flatpak.

**Comment by EvilSupahFly** [comment]
I actually tried to make Amulet into an AppImage, and had more trouble with that than the Flatpak. Despite having some internal textures missing in the flatpak version, at least the it ran on the first build.

**Comment by signalno11** [comment]
> I actually tried to make Amulet into an AppImage, and had more trouble with that than the Flatpak. Despite having some internal textures missing in the flatpak version, at least the it ran on the first build.

Seems about right. AppImages are truly horrible.

**Comment by gentlegiantJGC** [comment]
I have made some progress with a flatpak build.

@EvilSupahFly the texture issue you had was due to the mtime being set to 0 for some reason for those textures. That broke [this check](https://github.com/Amulet-Team/Minecraft-Model-Reader/blob/4be9a72aa2b70f60cc5948e02f355c1a51b30057/minecraft_model_reader/api/resource_pack/java/resource_pack_manager.py#L118-L121). I will fix it in the library.

**Comment by EvilSupahFly** [comment]
After all the debugging that I did, it never occurred to me that `mtime` would be a factor. 😳

**Comment by EvilSupahFly** [comment]
Having bought the basic $10 license for Amulet, I have now successfully built a flatpak version of Amulet 0.10.54. Everything I have is in [this repo](https://github.com/EvilSupahFly/Amulet-Flatpak/tree/main) - the manifests, metainfo files, a .desktop launcher, the .png icon, my modified sources, and even both the [flatpak binary](https://github.com/EvilSupahFly/Amulet-Flatpak/releases/download/0.10.54/amulet-x86_64-0.10.54.flatpak) and the repo I build locally.

I've tested the building process and the launching, and I updated the `requirements.txt` to reflect changes in Amulet's source code. Everything works as expected in the flatpak build - the flickering is gone and the textures all load properly now that the `mtime` issue has been addressed. Honestly, it looks really good now.

Now - in terms of this being a flatpak, there are several important things to note for building it and actually making it work (which should be obvious from my [extended manifest](https://github.com/EvilSupahFly/Amulet-Flatpak/blob/main/pip-gen.yaml)):
1. `- export SETUPTOOLS_SCM_PRETEND_VERSION=4.4.5` is required for `lz4`
2. Even with this override, I had to build a wheel from source with `python -m build` to make it work
3. `amulet-pybind11-extensions` must be installed before `amulet_rocksdb` or else the build fails when `amulet_rocksdb` runs its `setup.py` checks for installing
4. `amulet_rocksdb` also apparently required `cmake` from [Pypi](https://pypi.org/project/cmake/) which required `backend` first, and they had to be installed in the same step - `backend` then `cmake`
5. Like with `lz4`, I had to build a wheel locally for `cmake` and use that
6. These `build-commands` overrides were also required for `amulet-rocksdb` to install properly:      `- export VERSIONEER_OVERRIDE=1.0.2`
      `- export SETUPTOOLS_SCM_PRETEND_VERSION=1.0.2`
      `- export SETUPTOOLS_USE_DISTUTILS=stdlib`
7. Like with `lz4`, I had to build a wheel for `amulet_rocksdb` from source with `python -m build` to make it work
8. I included `pybind11` as a precaution and while it didn't cause any problems, it's probably fine to remove since `amulet_rocksdb` looks for `amulet-pybind11-extensions` and not the original `pybind11`

Flatpak definitely has some quirks, and the `pip` dependencies don't always get followed all the way through the whole chain, but on the whole, this was still better than trying to build an appimage. Side note - you can combine both of my YAML manifests into one larger single manifest and it will still build (provided you follow the proper indentation) if you want - I only had it broken into two separate files because it was easier to regenerate the requirements separately during testing..

<img width="2560" height="1410" alt="Image" src="https://github.com/user-attachments/assets/63767c64-da02-429d-946a-cb62129a4fb2" />

**Comment by EvilSupahFly** [comment]
No issues with the flatpak reading or writing Minecraft worlds either.

<img width="5120" height="1440" alt="Image" src="https://github.com/user-attachments/assets/7cad4885-786a-4420-a6c1-d5356b066199" />

<img width="5120" height="1440" alt="Image" src="https://github.com/user-attachments/assets/6b05f1ea-b8b0-4a98-b6c5-6a2dd7fc0aa8" />

**Comment by EvilSupahFly** [comment]
After some testing, I can confirm it works on both X11 and Wayland.

**Comment by gentlegiantJGC** [comment]
To simplify the build process and minimise the amount of work I have to do to maintain this I have decided to build all the python libraries in the host runner and then pass them to flatpak.

This is the github workflow
https://github.com/Amulet-Team/Amulet-Map-Editor/blob/6d3b0e2c65acc45706017cdd42482bb175ce560e/.github/workflows/build-flatpak.yml

This is the flatpak script
https://github.com/Amulet-Team/Amulet-Map-Editor/blob/6d3b0e2c65acc45706017cdd42482bb175ce560e/installer/com.amuletmc.amulet_map_editor.yml

**Comment by EvilSupahFly** [comment]
That's looking pretty good, except I had issues with Wayland based Linux distributions when I used the Ubuntu build of wxPython and used the Pypi build instead. But under Python 3.13, it could behave better, who knows.

**Comment by gentlegiantJGC** [comment]
What issues did you have? From memory there are a couple of wayland issues even when running from source. One related to mouse teleporting.
I used the pre-built wxpython because compiling it from source is a pain.

**Comment by gentlegiantJGC** [comment]
I have added a flatpak distribution to Gumroad on the beta tab

**Comment by EvilSupahFly** [comment]
> To simplify the build process and minimise the amount of work I have to do to maintain this I have decided to build all the python libraries in the host runner and then pass them to flatpak.
> 
> This is the github workflow https://github.com/Amulet-Team/Amulet-Map-Editor/blob/6d3b0e2c65acc45706017cdd42482bb175ce560e/.github/workflows/build-flatpak.yml
> 
> This is the flatpak script https://github.com/Amulet-Team/Amulet-Map-Editor/blob/6d3b0e2c65acc45706017cdd42482bb175ce560e/installer/com.amuletmc.amulet_map_editor.yml

Solid plan, especially if `flatpak-builder` uses the source to make wheels, because when the Python version in Flatpak's SDK gets updated, the libraries will be built against the new version every time, something that tripped me up on my first build attempt. 

😅

> What issues did you have? From memory there are a couple of wayland issues even when running from source. One related to mouse teleporting. I used the pre-built wxpython because compiling it from source is a pain.

The issue I had (with 0.10.43/.44) was that it didn't render anything at all under Wayland. That could just have been something related to my setup since I tested Wayland on EndeavourOS in a VM because my daily driver - Mint - uses X11. In my testing, X11 was always fine, aside from the missing textures and the blinking UI. Could have been a VM issue. 0.10.55 seems to be fine in my new CachyOS VM, so either the issue was resolved after subsequent updates, or my Endeavour VM had a bad setting somewhere.

`¯\_(ツ)_/¯`

**Comment by gentlegiantJGC** [comment]
I only give the flatpak [access to x11](https://github.com/Amulet-Team/Amulet-Map-Editor/blob/b7862d69163e7b252d74eeefe1aba540a51fa139/installer/com.amuletmc.amulet_map_editor.yml#L9).
I assume this will make it use x11 instead of wayland because there are some compatibility issues with wayland.
The most notable is that wayland does not allow mouse teleporation.

**Comment by TerminallyDied** [comment]
i think the pointer warp protocol should allow that
